version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: L@mpugn4n1
      POSTGRES_DB: sei
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - sei-network

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: L@mpugn4n1
      DB_NAME: sei
      NODE_ENV: development
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    networks:
      - sei-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:3001/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - sei-network

volumes:
  postgres_data:

networks:
  sei-network:
    driver: bridge