version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sei
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sei-network

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: L@mpugn4n1
      DB_NAME: postgres
    depends_on:
      - db
    networks:
      - sei-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - sei-network

volumes:
  postgres_data:

networks:
  sei-network:
    driver: bridge